version: '3'
services:

  weather_api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
